model PendulumFreeflyingSUM_Freeflying
  // Auto-generated by ModeGen

  parameter Real m = 1; // Bob mass
  parameter Real g = 9.81; // Gravity
  Real y;
  
  Real x;
  Real vx;
  Real vy;
  

equation
  vx = der(x);
  vy = der(y);
  m * der(vx) = 0;
  m * der(vy) = -m * g;

end PendulumFreeflyingSUM_Freeflying;
